# Generated by Django 5.0.3 on 2024-03-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_teacher_alter_student_grade_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ST_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher',
        ),
    ]
