# Generated by Django 5.0.3 on 2024-03-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_lecture_lecture_remove_student_st_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
