# Generated by Django 5.0.3 on 2024-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_student_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(related_name='lecture_stu', to='learning.student'),
        ),
    ]
